<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD 추가 -->
<!DOCTYPE memberList 
[
<!ELEMENT memberList (memberInfo+)>
<!ELEMENT memberInfo (name, telephone, curriculum?, zipCode, addr)>
<!-- curriculum 처럼 있기도하고 없기도 한 경우에는 ? 를 붙인다 -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT curriculum (sub+)>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT zipCode (#PCDATA)>
<!ELEMENT addr (#PCDATA)>
<!ATTLIST memberInfo mid CDATA #IMPLIED>
]>
<!-- 
#REQUIRED : 이 속성은 반드시 명시되어야 한다.
#IMPLIED : 이 속성은 명시되기도 하고, 명시되지 않기도 한다.
#FIXED 특정값 : 이 속성은 특정값으로 고정되어 사용된다.
 -->
<memberList>
	
	<memberInfo mid="1">
		<name>노노노</name>
		<telephone><![CDATA[010-1234-4567]]></telephone>
		<curriculum>
			<sub>JAVA SE</sub>
			<sub>ORACLE</sub>
			<sub><![CDATA[Servlet&JSP]]></sub>
		</curriculum>
		<zipCode>01234</zipCode>
		<addr>서울시 마포구 월드컵북로 150</addr>
	</memberInfo>
	
	<memberInfo mid="2">
		<name>김민민</name>
		<telephone><![CDATA[010-9987-8876]]></telephone>
		<zipCode>01285</zipCode>
		<addr>서울시 은평구 통일로 20</addr>
	</memberInfo>
	
	
</memberList>

































